# 线性代数
## 1.标量

In [3]:
#实例化标量

import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2.向量

In [4]:
#一维张量处理向量

x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
#通过索引访问向量中的元素

x[3]

tensor(3)

In [6]:
#调用内置len函数访问张量的长度

len(x)

4

In [8]:
#调用.shape属性访问向量的长度，并列出了沿每个轴的长度（维数）

x.shape

torch.Size([4])

## 3.矩阵

In [9]:
#指定两个分量创建矩阵

A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [10]:
#对矩阵进行转置

A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [11]:
#对称矩阵的转置等于自身 

B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [12]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 4.张量

In [13]:
#向量是一阶张量，矩阵是二阶张量。现在创建一个三阶张量

X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 5.张量算法的基本性质

In [14]:
#将两个相同形状的矩阵相加，会在这两个矩阵上执行元素加法

A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()    #通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [16]:
#矩阵按元素乘法——Hadamard积

A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [17]:
#张量乘以或加上一个标量不会改变形状，其中每个元素都会相乘相加

a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 6.降维

In [18]:
#对张量计算其元素的和

x = torch.arange(4, dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [19]:
#表示任意形状张量的元素和

A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [20]:
#为了通过求和所有行的元素降维，可以调用调和函数指定axis=0，沿0轴降维

A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [21]:
#指定axis=1将通过汇总所有列的元素降维（轴1）

A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [22]:
#沿着行和列对矩阵求和，等价于对矩阵所有元素求和

A.sum([0, 1])   # = A.sum()

tensor(190.)

In [23]:
#求平均值，将总和除以元素总数计算平均值

A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

In [25]:
#同样，计算平均值也可以沿指定轴降维

A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [26]:
#但有时求和要求维数不变

sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [27]:
#可以通过广播机制将A除以sum_A

A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [28]:
#如果想沿着某个轴计算元素累计总和，调用cumsum函数。此函数不会降低维度

A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

## 7.点积

In [29]:
#点积是相同位置的按元素乘积的和

y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [30]:
#可以通过元素乘法然后求和表示向量的点积

torch.sum(x * y)

tensor(6.)

## 8.矩阵-向量积

In [31]:
#矩阵-向量积使用和点积相同的mv函数，A的列维数（沿轴1的长度）必须与x的维数（长度）相同

A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 9.矩阵-矩阵乘法

In [32]:
#A是5X4，B是4X3，得到5X3的矩阵

B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 10.范数

In [33]:
#L2范数——向量元素平方和的平方根

u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [34]:
#L1范数——向量元素的绝对值之和

torch.abs(u).sum()

tensor(7.)

In [36]:
#Frobenius范数（Frobenius norm）是矩阵元素平方和的平方根

torch.norm(torch.ones((4, 16)))

tensor(8.)

## 练习

In [37]:
#证明一个矩阵A的转置的转置是A

A = torch.arange(12, dtype=torch.float32).reshape(2,6)
B = A.T
A == B.T

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True]])

In [40]:
#给出两个矩阵A和B，证明“转置的和”等于“和的转置”

B = A.clone()
X = A + B
A.T + B.T == X.T

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

In [42]:
#给定任意方阵A，A + A转置总是对称吗

A = torch.randn(3, 3)
B = A.T
X = A + B
A, B, X

(tensor([[-0.2390, -0.6896, -1.1550],
         [-0.3811, -0.8538, -2.0525],
         [-1.4261, -1.8762, -0.4872]]),
 tensor([[-0.2390, -0.3811, -1.4261],
         [-0.6896, -0.8538, -1.8762],
         [-1.1550, -2.0525, -0.4872]]),
 tensor([[-0.4780, -1.0707, -2.5811],
         [-1.0707, -1.7076, -3.9287],
         [-2.5811, -3.9287, -0.9744]]))

In [44]:
#形状为（2， 3， 4）的张量X，len(x)的输出结果是什么

X = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)
len(X)

2

In [51]:
#对于任意形状的张量X，len(x)是否总对应与X特定轴的长度，这个轴是什么

X = torch.randn(3, 4, 2, 2)
len(X)

3

In [53]:
#运行代码分析原因

A = torch.arange(9).reshape(3, 3)
A / A.sum(axis=1)

tensor([[0.0000, 0.0833, 0.0952],
        [1.0000, 0.3333, 0.2381],
        [2.0000, 0.5833, 0.3810]])

In [55]:
#一个(2, 3, 4)的张量，在轴0、1、2上求和输出是什么形状

B = torch.arange(24).reshape(2, 3, 4)
B0 = B.sum(axis=0)
B1 = B.sum(axis=1)
B2 = B.sum(axis=2)
B, B0, B1, B2

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))